import { FieldValue, type Firestore } from "firebase-admin/firestore";

export const COMMITMENT_TYPES = ["would_watch", "would_pay", "bring_to_city", "back_next_chapter"] as const;
export type CommitmentType = (typeof COMMITMENT_TYPES)[number];
export const followId = (projectId: string, uid: string) => `${projectId}_${uid}`;
export const commitmentId = (projectId: string, uid: string, type: CommitmentType) => `${projectId}_${uid}_${type}`;
export const voteId = (projectId: string, uid: string) => `${projectId}_${uid}`;
export const takeId = (projectId: string, uid: string) => `${projectId}_${uid}`;
export const replyId = (take: string, uid: string) => `${take}_${uid}`;
export function moveVoteCounts(counts: Record<string, number>, previous: string | undefined, next: string, active = true) {
  const result = { ...counts };
  if (previous && previous !== next) result[previous] = Math.max(0, (result[previous] ?? 0) - 1);
  if (active && previous !== next) result[next] = Math.max(0, (result[next] ?? 0) + 1);
  return result;
}

export class SocialError extends Error { constructor(readonly code: string, message: string, readonly status = 400) { super(message); } }
type Tx = FirebaseFirestore.Transaction;
// Firestore documents are intentionally schemaless at this boundary; route
// payloads are validated before they reach this store.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Data = Record<string, any>;

async function projectAndPathway(tx: Tx, db: Firestore, projectId: string, pathwayId?: string) {
  const projectRef = db.collection("projects").doc(projectId);
  const projectSnap = await tx.get(projectRef);
  if (!projectSnap.exists) throw new SocialError("project_not_found", "Project was not found.", 404);
  const project = (projectSnap.data() ?? {}) as Data;
  if (project.publicationStatus !== "published" || (project.moderationState !== undefined && project.moderationState !== "clear")) throw new SocialError("project_unavailable", "This project is not available.", 404);
  if (!pathwayId) return { projectRef, project };
  const cardId = project.latestCardVersionId;
  if (typeof cardId !== "string") throw new SocialError("pathway_unavailable", "That pathway is not available.", 400);
  const cardSnap = await tx.get(db.collection("scoutCards").doc(cardId));
  const card = (cardSnap.data() ?? {}) as Data;
  const pathways = Array.isArray(card.pathways) ? card.pathways : [];
  if (!pathways.some((p: Data) => p.id === pathwayId && (card.visibility === undefined || card.visibility === "public"))) throw new SocialError("pathway_unavailable", "That pathway is not available.", 400);
  return { projectRef, project };
}
const inc = (n: unknown, delta: number) => Math.max(0, (typeof n === "number" ? n : 0) + delta);

export function createSocialStore(db: Firestore) {
  return {
    follow(projectId: string, uid: string, active: boolean) { return db.runTransaction(async tx => { const { projectRef, project } = await projectAndPathway(tx, db, projectId); const ref = db.collection("follows").doc(`${projectId}_${uid}`); const old = (await tx.get(ref)).data() as Data | undefined; const was = old?.active === true; if (was !== active) tx.set(projectRef, { followerCount: inc(project.followerCount, active ? 1 : -1), updatedAt: FieldValue.serverTimestamp() }, { merge: true }); tx.set(ref, { projectId, uid, active, updatedAt: FieldValue.serverTimestamp(), ...(active ? { createdAt: old?.createdAt ?? FieldValue.serverTimestamp() } : {}) }, { merge: true }); return { active }; }); },
    commitment(projectId: string, uid: string, type: CommitmentType, active: boolean, city?: string) { return db.runTransaction(async tx => { const { projectRef, project } = await projectAndPathway(tx, db, projectId); if (type === "bring_to_city" && active && !city?.trim()) throw new SocialError("city_required", "A city is required for this commitment."); const ref = db.collection("commitments").doc(`${projectId}_${uid}_${type}`); const old = (await tx.get(ref)).data() as Data | undefined; const was = old?.active === true; if (was !== active) { const counts = { ...(project.commitmentCounts ?? {}) }; counts[type] = inc(counts[type], active ? 1 : -1); tx.set(projectRef, { commitmentCounts: counts, updatedAt: FieldValue.serverTimestamp() }, { merge: true }); } tx.set(ref, { projectId, uid, type, active, ...(city?.trim() ? { city: city.trim() } : {}), updatedAt: FieldValue.serverTimestamp(), ...(old?.createdAt ? {} : { createdAt: FieldValue.serverTimestamp() }) }, { merge: true }); return { active, type, ...(city?.trim() ? { city: city.trim() } : {}) }; }); },
    vote(projectId: string, uid: string, pathwayId: string | undefined, active: boolean) { return db.runTransaction(async tx => { if (active && !pathwayId) throw new SocialError("invalid_vote", "A pathway is required."); const { projectRef, project } = await projectAndPathway(tx, db, projectId, active ? pathwayId : undefined); const ref = db.collection("pathwayVotes").doc(voteId(projectId, uid)); const old = (await tx.get(ref)).data() as Data | undefined; const previous = old?.active === true ? old.pathwayId as string : undefined; const target = pathwayId ?? previous; if (active && target && previous !== target) { const counts = { ...(project.pathwayVoteCounts ?? {}) }; if (previous) counts[previous] = inc(counts[previous], -1); counts[target] = inc(counts[target], 1); tx.set(projectRef, { pathwayVoteCounts: counts }, { merge: true }); } else if (active && target && old?.active !== true) { const counts = { ...(project.pathwayVoteCounts ?? {}) }; counts[target] = inc(counts[target], 1); tx.set(projectRef, { pathwayVoteCounts: counts }, { merge: true }); } else if (!active && previous) { const counts = { ...(project.pathwayVoteCounts ?? {}) }; counts[previous] = inc(counts[previous], -1); tx.set(projectRef, { pathwayVoteCounts: counts }, { merge: true }); } tx.set(ref, { projectId, uid, ...(target ? { pathwayId: target } : {}), active, visibility: "public", updatedAt: FieldValue.serverTimestamp(), ...(old?.createdAt ? {} : { createdAt: FieldValue.serverTimestamp() }) }, { merge: true }); return { active, pathwayId: target }; }); },
    take(projectId: string, uid: string, input: { whyItShouldGrow: string; preferredPathwayId: string; audienceNote?: string }, active: boolean, edit = false) { return db.runTransaction(async tx => { const { projectRef, project } = await projectAndPathway(tx, db, projectId, active ? input.preferredPathwayId : undefined); const ref = db.collection("takes").doc(takeId(projectId, uid)); const voteRef = db.collection("pathwayVotes").doc(voteId(projectId, uid)); const old = (await tx.get(ref)).data() as Data | undefined; const priorVote = (await tx.get(voteRef)).data() as Data | undefined; const was = old?.active === true; const previous = priorVote?.active === true ? priorVote.pathwayId as string : undefined; if (was !== active) { const replySnap = await tx.get(db.collection("replies").where("takeId", "==", ref.id).where("active", "==", true)); tx.set(projectRef, { takeCount: inc(project.takeCount, active ? 1 : -1), replyCount: inc(project.replyCount, active ? replySnap.docs.length : -replySnap.docs.length), updatedAt: FieldValue.serverTimestamp() }, { merge: true }); } if (active && previous !== input.preferredPathwayId) { const counts = { ...(project.pathwayVoteCounts ?? {}) }; if (previous) counts[previous] = inc(counts[previous], -1); counts[input.preferredPathwayId] = inc(counts[input.preferredPathwayId], 1); tx.set(projectRef, { pathwayVoteCounts: counts }, { merge: true }); tx.set(voteRef, { projectId, uid, pathwayId: input.preferredPathwayId, active: true, visibility: "public", updatedAt: FieldValue.serverTimestamp(), ...(priorVote?.createdAt ? {} : { createdAt: FieldValue.serverTimestamp() }) }, { merge: true }); } else if (!active && previous) { const counts = { ...(project.pathwayVoteCounts ?? {}) }; counts[previous] = inc(counts[previous], -1); tx.set(projectRef, { pathwayVoteCounts: counts }, { merge: true }); tx.set(voteRef, { active: false, updatedAt: FieldValue.serverTimestamp() }, { merge: true }); } tx.set(ref, { ...(active ? input : {}), projectId, uid, active, status: active ? "published" : "withdrawn", ...(edit ? { edited: true } : {}), updatedAt: FieldValue.serverTimestamp(), ...(old?.createdAt ? {} : { createdAt: FieldValue.serverTimestamp() }) }, { merge: true }); return { takeId: ref.id, active }; }); },
    reply(takeId: string, uid: string, body: string, mode: "create" | "edit" | "withdraw") { return db.runTransaction(async tx => { const takeRef = db.collection("takes").doc(takeId); const takeSnap = await tx.get(takeRef); if (!takeSnap.exists || (takeSnap.data() as Data)?.active !== true) throw new SocialError("take_unavailable", "That Take is not available.", 404); const take = takeSnap.data() as Data; const projectRef = db.collection("projects").doc(String(take.projectId)); const projectSnap = await tx.get(projectRef); const project = (projectSnap.data() ?? {}) as Data; if (!projectSnap.exists || project.publicationStatus !== "published" || (project.moderationState !== undefined && project.moderationState !== "clear")) throw new SocialError("project_unavailable", "This project is not available.", 404); const ref = db.collection("replies").doc(replyId(takeId, uid)); const old = (await tx.get(ref)).data() as Data | undefined; if (mode === "create" && old?.active === true) throw new SocialError("reply_exists", "You already replied to this Take.", 409); if (mode === "edit" && old?.active !== true) throw new SocialError("reply_not_found", "Reply was not found.", 404); const was = old?.active === true; const active = mode !== "withdraw"; if (was !== active) { tx.update(takeRef, { replyCount: inc(take.replyCount, active ? 1 : -1), updatedAt: FieldValue.serverTimestamp() }); tx.update(projectRef, { replyCount: inc(project.replyCount, active ? 1 : -1), updatedAt: FieldValue.serverTimestamp() }); } tx.set(ref, { takeId, projectId: take.projectId, uid, ...(active ? { body, edited: mode === "edit" } : {}), active, status: active ? "published" : "withdrawn", visibility: "public", updatedAt: FieldValue.serverTimestamp(), ...(old?.createdAt ? {} : { createdAt: FieldValue.serverTimestamp() }) }, { merge: true }); return { replyId: ref.id, active }; }); },
  };
}
